### PR TITLE
Handle errors from 'manage add'

### PR DESCRIPTION
**Pull request by zprogd**
When 'manage add' has errors:
- use log->error instead of log->info
- do exit(1) instead of normal exit with 'done'

### CODE REVIEW

**Comment by zprogd** [comment]
https://github.com/xsawyerx/pakket/issues/195

**Comment by xsawyerx** [comment]
The only problem here is that we're exiting as soon as it fails. This means we cannot collect many that failed. Maybe we should return 1 from that subroutine and then the caller would exit with what it got.

@mickeyn, @gonzus, thoughts?

**Comment by gonzus** [comment]
Right, have that routine return the number of errors (0 => none), and let the caller decide whether exiting is the right way to go. That sounds reasonable to me.

**Comment by mickeyn** [comment]
I don't see a problem with the suggested change as it happens at the end of the run.
I would recommend to sort the keys so the output would be more consistent.

**Comment by xsawyerx** [comment]
@zprogd Up to you. :)

**Pull request closed without merging**
